### ISSUE TITLE
Be consistent on which controls have caveat inputs for documented exceptions

### ISSUE THREAD

**Issue by wdower** [mitre/redhat-enterprise-linux-9-stig-baseline#39]
Some controls (see controls/SV-257803.rb) have caveats in the check text for ISSO waivers for a package being present or not present.

We should determine if this language indicates that a control should have an explicit input for that package being a documented requirement, and if it does, update all controls that include one of the caveats.

**Comment by ejaronne** [comment]
Yes, but each case should be considered carefully
But, for any of the "documented with the ISSO as an operational requirement" of which I saw 48 in v1r3.

create a sensible T/F logic input like "core_dumps_documented_by_ISSO_as_operational_requirement"

If set to True, set Impact to zero (which will calculate to be Not Applicable), and set a skip message like: "This requirement is not applicable since it is documented by the ISSO as an operational requirement"

AND run the tests anyway for situational awareness.
